#!/usr/bin/env sh

# fetch current branch name 
BRANCH=`git branch --no-color | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`

sphinx-build -aE . _build/html/$BRANCH

for file in `find _build/html/$BRANCH -type f -name "*.html"`
do
    sed -i '' 's/index.html//g' $file
done
